### ISSUE TITLE
Considering using ArangoDB GO driver

### ISSUE THREAD

**Issue by sandrokeil** [sandrokeil/arangodb-php-driver#11]
It looks like the [ArangoDB GO driver](https://github.com/search?q=org%3Aarangodb+go) is more mature than the c++ driver. So we can use them and call it from c++.

GO has different [build modes](https://golang.org/cmd/go/#hdr-Description_of_build_modes), so maybe it's really easy to use. /cc @martin-schilling

**Comment by sandrokeil** [comment]
Looks like we have to create an own main package because of building the go driver leads to errors.
```
-buildmode=c-archive requires exactly one main package
-buildmode=c-shared requires exactly one main package
```

**Comment by sandrokeil** [comment]
Here is an [example blog post](https://blog.gopheracademy.com/advent-2015/libc-hooking-go-shared-libraries/) how to [build c-shared](https://github.com/mattbostock/go-ldpreload-backdoor/blob/master/main.go).

**Comment by sandrokeil** [comment]
@martin-schilling I've created a [new branch golang](https://github.com/sandrokeil/arangodb-php-driver/tree/goloang) which builds the c archive from go-velocypack. Now we have to find a way to call `test()` from the php-cpp main file. I guess there is some linker fun ;-)

We have to check what does this mean exactly

> The only callable symbols will be those functions exported using a cgo //export comment

**Comment by sandrokeil** [comment]
@martin-schilling I've added a [test case](https://github.com/sandrokeil/arangodb-php-driver/commit/da35c002b75386371adec86f12ba00c709b24143). Now it's your turn. ;-) We have the following issues:

```
g++: warning: go/arangodb.a: linker input file unused because linking not done
```

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/arangodb.so' - /usr/lib/php/20160303/arangodb.so: 
invalid ELF header in Unknown on line 0
PHP Fatal error:  Uncaught Error: Call to undefined function vpack() in /app/test.php:13
Stack trace:
#0 {main}
  thrown in /app/test.php on line 13

Fatal error: Uncaught Error: Call to undefined function vpack() in /app/test.php:13
Stack trace:
#0 {main}
  thrown in /app/test.php on line 13
```

**Comment by martin-schilling** [comment]
@sandrokeil The linking stuff should hopefully be fixed now. I think the next aim should be getting some database interaction going in a test case.

**Comment by sandrokeil** [comment]
@martin-schilling Thanks so much. I want to try the vpack example from the master branch first and maybe the go return value mapping. You can bring a new PR with the connection if you have time. 👍

**Comment by sandrokeil** [comment]
There is an important [issue](https://github.com/golang/go/issues/18412)

> The correct program should use a type defined in C, rather than in Go, because otherwise the external C programs have to manually define a C struct matching the Go struct, which is non-trivial and error-prone.

**Comment by sandrokeil** [comment]
We stick with C++.
